#!/usr/bin/env bash
# This script does the following:
#   1. updates packages
#   2. installs Nginx
#   3. sets listening port on 80
#   4. sets `Hello World!` as a default response
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
new_server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	root /var/www/html;
	index index.html index.nginx-debian.html;

	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me)
	{
		rewrite ^ https://www.youtube.com/watch?v=VZrDxD0Za9I permanent;
	}
}
"
sudo bash -c "echo -e '$new_server_config' > /etc/nginx/sites-enabled/default"
sudo service nginx start
sudo service nginx restart
