#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "frontend http_front
        bind *:80
        mode http
        default_backend http_back

backend http_back
        balance roundrobin
        server webserver1 54.173.35.201:80 check
        server webserver2 34.232.69.227:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
