#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
sudo chown "$USER":"$USER" /etc/default/haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo -e "\nfrontend haproxy-loadbalancer\n\tbind *:80\n\tmode http\n\tdefault_backend nginx-webservers\nbackend nginx-webservers\n\tbalance roundrobin\n\tserver 495241-web-01\t3.83.245.203:80 check\n\tserver 495241-web-02\t54.173.35.201:80 check\n" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy start
