#!/usr/bin/env bash
# Print "Best School" except for 9th time, say "Hi"
var=1
while [ $var -le 10 ]
do
    echo "Best School"
    if [ $var -eq 9 ]
    then
        echo "Hi"
    fi
    var=$(( var + 1 ))
done
