#!/usr/bin/env bash
# debug webserver
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx "service nginx restart"
